### ISSUE TITLE
Reading raw binary digital values

### ISSUE THREAD

**Issue by cloud8421** [fhunleth/elixir_ale#17]
Hello,

I'll start by saying that my hardware experience is very limited, so I may say something wrong. Please let me know if that's the case.

I'm trying to read data from [this temperature/etc. digital sensor](https://www.adafruit.com/products/386) from a Raspberry PI 3.

It's a nerves `~> 0.3.0` application, using `~> 0.5.3` for elixir_ale.

As far as I can see at [this line in the c source code](https://github.com/fhunleth/elixir_ale/blob/master/src/gpio_port.c#L179) the value from the sensor is "discarded" to return either 1 or 0. Is that correct?

I was thinking to try to extend that myself and send a PR, but I wanted to check first if it's a good idea or not. Thanks!

**Comment by fhunleth** [comment]
Hi - GPIO's can only be low (0) or high (1). There are no other values. I didn't look at the datasheet for the sensor, but from the webpage it looks like it has its own special form of morse code for getting temperature values from it.

I see that you found the slack channel for help. Hopefully others will be able to assist. I'll be there this evening.
