### ISSUE TITLE
GenEvent

### ISSUE THREAD

**Issue by ulve** [fhunleth/elixir_ale#22]
Instead of sending messageses from Gpio when input changes how about changing it to a proper GenEvent?

**Comment by fhunleth** [comment]
I'm not a fan of GenEvent, and I'm actually trying to move away from it. When this has come up in the past, my recommendation was to route the events over `gproc`. I haven't gotten to really dig into `GenStage` yet, but that may be a better option now. As for `elixir_ale`, my view is that it should be kept simple and that users should wrap calls to it for their particular hardware. That code could then decide the proper event notification mechanism and possibly give higher level and more meaningful events.
