### ISSUE TITLE
make it possible to configure pull up or pull down resistor

### ISSUE THREAD

**Issue by tcoopman** [fhunleth/elixir_ale#59]
As far as I can see, it's not possible to configure a GPIO input as pull down or pull up resistor. Can you make this possible?

**Comment by fhunleth** [comment]
This is frustratingly platform-dependent and has required writing memory mapped registers behind the Linux kernel's back. I'll look at the current state of affairs with Linux for Elixir ALE 2.0, but in the mean time, check out https://github.com/Hermanverschooten/gpio_rpi.

**Comment by fhunleth** [comment]
We're addressing pull up/pull down support in https://github.com/elixir-circuits/circuits_gpio.
