### ISSUE TITLE
elxir ale is build for different host?

### ISSUE THREAD

**Issue by ychaudhari7** [fhunleth/elixir_ale#72]
Below is my environment for elixir and nerves

    Elixir version (Elixir 1.8.1 (compiled with Erlang/OTP 21)):
    
    Nerves environment: (`|nerves_bootstrap| Environment Package List
    
    Pkg: nerves_system_br
    Vsn: 1.7.0
    Type: system_platform
    BuildRunner: {nil, []}
    
    Pkg: nerves_system_rpi0
    Vsn: 1.7.0
    Type: system
    BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}
    
    Pkg: nerves_toolchain_armv6_rpi_linux_gnueabi
    Vsn: 1.1.0
    Type: toolchain
    BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}
    
    Pkg: nerves_toolchain_ctng
    Vsn: 1.5.0
    Type: toolchain_platform
    BuildRunner: {nil, []}
    
    |nerves_bootstrap| Loadpaths Start
    
    Nerves environment
    MIX_TARGET: rpi0
    MIX_ENV: dev
    
    |nerves_bootstrap| Environment Variable List
    target: rpi0
    toolchain: /home/ganesh/.nerves/artifacts/nerves_toolchain_armv6_rpi_linux_gnueabi-linux_x86_64-1.1.0
    system: /home/ganesh/.nerves/artifacts/nerves_system_rpi0-portable-1.7.0
    app: /home/ganesh/exercism/myelixircode/nerves_examples/hello_network
    
    |nerves_bootstrap| Loadpaths End

I am using elixir ale 1.2 my target is rpi0 but when I do `mix deps.get` then `mix firmware` I get 

> Updating base firmware image with Erlang release...
> scrub-otp-release.sh: ERROR: Unexpected executable format for '/home/ganesh/exercism/nerves/nerves_examples/hello_network/_build/_nerves-tmp/rootfs-additions/srv/erlang/lib/elixir_ale-1.2.1/priv/ale'
> 
> Got:
>  readelf:Advanced Micro Devices X86-64;0x0
> 
> Expecting:
>  readelf:ARM;0x5000200, Version5 EABI, soft-float ABI
> 
> This file was compiled for the host or a different target and probably
> will not work.
> 
> Check the following:
> 
> 1. Are you using a path dependency in your mix deps? If so, run
>    'mix clean' in that directory to avoid pulling in any of its
>    build products.
> 
> 2. Did you recently upgrade to Nerves 1.3 or Distillery 2.0? Make
>    sure that your 'rel/config.exs' has 'plugin Nerves'. See
>    https://hexdocs.pm/nerves/updating-projects.html#updating-from-v1-0-to-v1-3-0
> 
> 3. Did you recently upgrade or change your Nerves system? If so,
>    try cleaning and rebuilding this project and its deps.
> 
> 4. Are you building outside of Nerves' mix integration? If so,
>    make sure that you've sourced 'nerves-env.sh'.
> 
> If you're still having trouble, please file an issue on Github
> at https://github.com/nerves-project/nerves_system_br/issues.
> 
> ** (Mix) Nerves encountered an error. %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: true}
> 

How can I make it work rpi0 I am giving correct target version here so why it is compiled for different host?

**Comment by fhunleth** [comment]
Is it possible for you to use one of the `circuits_*` libraries instead? [Elixir Circuits](https://elixir-circuits.github.io/) is Elixir/ALE 2.0 (but renamed) and I'm trying to encourage people to use it instead.

The quick way to get around this with Elixir/ALE is to clean the build directory and build again. You should run into this with the Circuits libraries.
